### PR TITLE
FAQ

### PR DESCRIPTION
**Pull request by joemart**
Added FAQ page. Still needs a theme. It currently displays at the top of the page

### CODE REVIEW

**Comment by olessiap** [comment]
love the hover effect, great job @joemart! My only suggestion is to clean up the CSS a bit and remove extra white spaces and tabs. ;) 
Also, are we going to stick to a design pattern in terms of styling? I noticed the skeleton is written with styled components. I personally haven't built anything with styled components other than using some libraries that already have them as defaults but I'm down to learn it and incorporate it.
@nikhil-g777

**Comment by joemart** [comment]
Definitely not the final version, it will most definitely improve in future versions.

**Comment by nikhil-g777** [comment]
@olessiap You're right, I think we should stick to one styling pattern throughout the codebase. @joemart could you modify this code such that we use styled components. Let me know if you think otherwise or have any questions

**Comment by joemart** [comment]
@nikhil-g777 Absolutely. I'll be doing that right now. I'm not sure about the artistic design though. I just wanted to put something there. 
@olessiap I'm also new to styled components, hah! You can most definitely learn it quick!

**Comment by nikhil-g777** [comment]
@joemart I think you can move the FAQ.js file into the pages folder so that we can maintain the same structure

**Comment by joemart** [comment]
Absolutely. Tomorrow, I'll do that.

**Pull request merged**
